service: fb-mim-checker

useDotenv: true

provider:
  name: aws
  runtime: python3.8
  memorySize: 128
  region: eu-central-1
  stage: ${opt:stage, 'production'}
  lambdaHashingVersion: 20201221
  environment:
    PROJECT: ${self:service}
    EMAIL: ${env:EMAIL}
    EMAIL_PASSWORD: ${env:EMAIL_PASSWORD}
    SMTP_SERVER: ${env:SMTP_SERVER}
    TWILIO_NUMBER: ${env:TWILIO_NUMBER}
    TWILIO_SID: ${env:TWILIO_SID}
    TWILIO_AUTH: ${env:TWILIO_AUTH}
    SLACK_WEBHOOK: ${env:SLACK_WEBHOOK}


custom:
  pythonRequirements:
    dockerizePip: non-linux

plugins:
  - serverless-python-requirements
functions:
  run:
    handler: <<FILL OUT>>
    events:
      - schedule: rate(60 minutes)